version: "2"

services:
  web:
    container_name: php5.6
    build: ./docker/php
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - ./docker/www:/var/www/html

  db:
    container_name: mysql
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - ./docker/db/gestion_produits.sql:/docker-entrypoint-initdb.d/gestion_produits.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gestion_produits