version: "3"

services:
  web:
    container_name: php5.6
    build: ./docker/php
    ports:
      - 80:80
    links:
      - db
      - minio
    volumes:
      - ./docker/www:/var/www/html
    networks:
      frontend:
        ipv4_address: 172.28.1.1

  db:
    container_name: mysql
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./docker/db/gestion_produits.sql:/docker-entrypoint-initdb.d/gestion_produits.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gestion_produits
    networks:
      frontend:
        ipv4_address: 172.28.1.2

  minio:
    container_name: minio
    image: minio/minio
    ports:
      - 9000:9000
    volumes:
      - ./docker/minio-data:/export
    environment:
      MINIO_ACCESS_KEY: P98T0S2L6ITESY94TZ5Z
      MINIO_SECRET_KEY: TLSqMqtnYfyJas1ocPdXUqLx30HdW2Y9RCJY2G
    command: server /export
    networks:
      frontend:
        ipv4_address: 172.28.1.3

networks:
  frontend:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16